from app.models.answer import Answer
from app.models.user import UserModel
from app.models.user_roles_assignments import UserRoleAssignment
from app.models.requirements_query import RequirementsQuery
from app.models.permit_renewals import PermitRenewal
from app.models.procedures import Procedure
from app.models.auth_user_groups import AuthUserGroup
from app.models.auth_user_user_permissions import AuthUserUserPermission
from app.models.auth_token import AuthToken
from app.models.auth_permission import AuthPermission
from app.models.auth_group import AuthGroup
from app.models.auth_group_permissions import AuthGroupPermission
from app.models.user_roles import UserRoleModel
from app.models.municipality import Municipality
from app.models.map_layers import MapLayer 
from app.models.sub_role import SubRoleModel
from app.models.technical_sheets import TechnicalSheet
from app.models.technical_sheet_downloads import TechnicalSheetDownload
from app.models.business_license import BusinessLicense
from app.models.business_license_status_log import BusinessLicenseStatusLog
from app.models.provisional_openings import ProvisionalOpening
from app.models.zoning_control_regulations import ZoningControlRegulation
from app.models.procedure_registrations import ProcedureRegistration
from app.models.business_types import BusinessType
from app.models.business_type_config import BusinessTypeConfig
from app.models.zoning_impact_level import ZoningImpactLevel
from app.models.field import Field
from app.models.requirements import Requirement
from app.models.business_license_histories import BusinessLicenseHistory
from app.models.urban_development_zonings import UrbanDevelopmentZoning
from app.models.urban_development_zonings_standard import UrbanDevelopmentZoningStandard
from app.models.municipality_map_layer_base import MunicipalityMapLayerBase
from app.models.base_map_layer import BaseMapLayer
from app.models.base_neighborhood import BaseNeighborhood
from app.models.base_locality import BaseLocality
from app.models.economic_units_directory import EconomicUnitsDirectory
from app.models.economic_activity_base import EconomicActivityBase
from app.models.municipality_signature import MunicipalitySignature
from app.models.inactive_businesses import InactiveBusiness
from app.models.business_line import BusinessLine
from app.models.business_sectors import BusinessSector
from app.models.business_sector_certificates import BusinessSectorCertificate
from app.models.business_sector_configurations import BusinessSectorConfiguration
from app.models.business_sector_impacts import BusinessSectorImpact
from app.models.building_footprints import BuildingFootprint
from app.models.land_parcel_mapping import LandParcelMapping
from app.models.dependency_reviews import DependencyReview
from app.models.dependency_resolutions import DependencyResolution
from app.models.blog import Blog
from app.models.recover_password import PasswordRecovery
from app.models.business_signatures import BusinessSignature
from app.models.business_logs import BusinessLog
from app.models.business_line_log import BusinessLineLog
from app.models.issue_resolution import IssueResolution
from app.models.reviewers_chat import ChatReviewer
from app.models.answers_json import AnswerJSON
from app.models.notifications import Notification
from app.models.departments import (
    Department, DepartmentRole, RequirementDepartmentAssignment,
    ProcedureDepartmentFlow, DependencyReviewWorkflow
)

# SQLAlchemy will configure mappers automatically when needed