from sqlalchemy import Column, BigInteger, Integer, String, Text, DateTime, ForeignKey
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from config.settings import Base


class BusinessLicenseHistory(Base):
    __tablename__ = 'business_license_histories'
    
    id = Column(BigInteger, primary_key=True, autoincrement=True)
    license_folio = Column(String(255), nullable=True)
    issue_date = Column(String(255), nullable=True)
    business_line = Column(String(255), nullable=True)
    detailed_description = Column(String(255), nullable=True)
    business_line_code = Column(String(100), nullable=True)
    business_area = Column(String(255), nullable=True)
    street = Column(String(100), nullable=True)
    exterior_number = Column(String(100), nullable=True)
    interior_number = Column(String(50), nullable=True)
    neighborhood = Column(String(50), nullable=True)
    cadastral_key = Column(String(100), nullable=True)
    reference = Column(String(100), nullable=True)
    coordinate_x = Column(String(30), nullable=True)
    coordinate_y = Column(String(30), nullable=True)
    owner_first_name = Column(String(100), nullable=True)
    owner_last_name_p = Column(String(100), nullable=True)
    owner_last_name_m = Column(String(100), nullable=True)
    user_tax_id = Column(String(25), nullable=True)
    national_id = Column(String(25), nullable=True)
    owner_phone = Column(String(25), nullable=True)
    business_name = Column(String(50), nullable=True)
    owner_email = Column(String(100), nullable=True)
    owner_street = Column(String(100), nullable=True)
    owner_exterior_number = Column(String(100), nullable=True)
    owner_interior_number = Column(String(50), nullable=True)
    owner_neighborhood = Column(String(50), nullable=True)
    alcohol_sales = Column(String(50), nullable=True)
    schedule = Column(String(100), nullable=True)
    municipality_id = Column(Integer, ForeignKey('municipalities.id'), nullable=True)
    status = Column(Integer, nullable=True)
    deleted_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, nullable=True, default=func.now())
    updated_at = Column(DateTime, nullable=True, default=func.now(), onupdate=func.now())
    applicant_first_name = Column(String(255), nullable=True)
    applicant_last_name_p = Column(String(255), nullable=True)
    applicant_last_name_m = Column(String(255), nullable=True)
    applicant_user_tax_id = Column(String(255), nullable=True)
    applicant_national_id = Column(String(255), nullable=True)
    applicant_phone = Column(String(255), nullable=True)
    applicant_street = Column(String(255), nullable=True)
    applicant_email = Column(String(255), nullable=True)
    applicant_postal_code = Column(String(255), nullable=True)
    owner_postal_code = Column(String(255), nullable=True)
    property_street = Column(String(255), nullable=True)
    property_neighborhood = Column(String(255), nullable=True)
    property_interior_number = Column(String(255), nullable=True)
    property_exterior_number = Column(String(255), nullable=True)
    property_postal_code = Column(String(255), nullable=True)
    property_type = Column(String(255), nullable=True)
    business_trade_name = Column(String(255), nullable=True)
    investment = Column(String(255), nullable=True)
    number_of_employees = Column(String(255), nullable=True)
    number_of_parking_spaces = Column(String(255), nullable=True)
    license_year = Column(String(255), nullable=True)
    license_type = Column(String(255), nullable=True)
    license_status = Column(String(255), nullable=True)
    reason = Column(String(255), nullable=True)
    deactivation_status = Column(String(255), nullable=True)
    payment_status = Column(String(255), nullable=True)
    opening_time = Column(String(255), nullable=True)
    closing_time = Column(String(255), nullable=True)
    alternate_license_year = Column(String(255), nullable=True)
    payment_user_id = Column(Integer, ForeignKey('users.id'), nullable=True)
    payment_date = Column(DateTime, nullable=True)
    scanned_pdf = Column(String(2000), nullable=True)
    step_1 = Column(Integer, nullable=True)
    step_2 = Column(Integer, nullable=True)
    step_3 = Column(Integer, nullable=True)
    step_4 = Column(Integer, nullable=True)
    minimap_url = Column(Text, nullable=True)
    reason_file = Column(Text, nullable=True)
    status_change_date = Column(DateTime, nullable=True)

    municipality = relationship("Municipality", back_populates="business_license_histories")
    payment_user = relationship("UserModel", back_populates="business_license_histories")
